---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: hub.comcast.net/ottx/thor-xre-build-tools
    tag: latest

inputs:
  - name: scripts

outputs:
  - name: got_token

run:
  path: scripts/tasks/get_eks_auth_token.sh