---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: 23380/test-image-9
    tag: latest

inputs:
  - name: gdt-testing-phase

outputs:
  - name: got_token

run:
  path: gdt-testing-phase/ci/tasks/get_eks_auth_token.sh