---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: hub.comcast.net/svc-rdk-analytics-gdt-artifact/hello-world-dev
    username: svc-gdtanalytics
    password: B,TFS2lNEqH~q-zc8N3I>iTjzn7qnItm
    tag: latest

inputs:
  - name: scripts

outputs:
  - name: got_token

run:
  path: scripts/ci/tasks/get_eks_auth_token.sh