---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: https://mujahid9503.github.io/gdt-helm/
    tag: latest

inputs:
  - name: scripts

outputs:
  - name: got_token

run:
  path: scripts/ci/tasks/get_eks_auth_token.sh