---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: yriscob/java17-maven3.3.9-builder
    tag: latest

inputs:
  - name: gdt-testing-phase
    path: gdt-testing-phase/
run:
  path: /bin/sh
  args:
  - -c
  - |
    apt update
    apt install -y openjdk-17-jdk
    java -version
    cd gdt-testing-phase/
    apt install -y maven
    mvn -N wrapper:wrapper
    mvn clean verify
outputs:
  - name: gdt-testing-phase