---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: yriscob/java17-maven3.3.9-builder
    tag: latest

inputs:
  - name: gdt-testing-phase
    path: gdt-testing-phase/
run:
  path: /bin/sh
  args:
  - -c
  - |
    java -version
    cd gdt-testing-phase/
    mvn clean package
outputs:
  - name: gdt-testing-phase