---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: benturner/debiangit
    tag: 0.0.1

inputs:
  - name: gdt-testing-phase
    path: gdt-testing-phase/
run:
  path: /bin/sh
  args:
  - -c
  - |
    apt update
    apt install -y openjdk-17-jdk
    java -version
    cd gdt-testing-phase/
    apt install -y maven
    mvn clean package
outputs:
  - name: gdt-testing-phase