resource_types:
- name: helm
  type: docker-image
  source:
    repository: typositoire/concourse-helm3-resource

resources:
  - name: gdt-testing-phase
    type: git
    webhook_token: ((github-webhook-token))
    source:
      uri: https://github.com/mujahid9503/gdt-helm.git
      branch: main
      username: ((git-username))
      password: ((git-password))

  - name: docker-hub
    type: docker-image
    source:
      username: ((hub-username))
      password: ((hub-password))
      repository: 23380/test-image-9
      tag: 1.0.0

  - name: helm-deploy-mumbai
    type: helm
    source:
      cluster_url: https://75D5EF5B0DBF24B3752B4BE445E12984.gr7.ap-south-1.eks.amazonaws.com
      cluster_ca: ((cluster-ca-mumbai))
      token: ((token-mumbai))
      repos:
        - name: git-repo
          url: https://mujahid9503.github.io/gdt-helm/

  - name: helm-deploy-london
    type: helm
    source:
      cluster_url: https://0B3E842D45FDE12169A59FB07EB60DF6.gr7.eu-west-2.eks.amazonaws.com
      cluster_ca: ((cluster-ca-london))
      token: ((token-london))
      repos:
        - name: git-repo
          url: https://mujahid9503.github.io/gdt-helm/

jobs:
- name: build-and-deploy
  serial: false
  plan:
  - get: gdt-testing-phase
    trigger: true
  - task: jar-build-gdt
    file: gdt-testing-phase/ci/tasks/maven_build.yml
  - put: docker-hub
    params:
      build: gdt-testing-phase/
  - put: helm-deploy-mumbai
    params:
      chart: git-repo/helmchart
      release: deploy
      uninstall: false
  - put: helm-deploy-london
    params:
      chart: git-repo/helmchart
      release: deploy
      uninstall: false